### ISSUE TITLE
Unable to open config file on OS X.

### ISSUE THREAD

**Issue by ehkropf** [timholy/Images.jl#363] opened 2015-09-21 17:34 UTC
I get the following error when trying a `convert(Image, matrixvar)` where `matrixvar` is of type `Array{Float64,2}`:
```
UnableToOpenConfigureFile `coder.xml' @ warning/configure.c/GetConfigureOptions/706

 in error at error.jl:21
 in error at /Users/zzz/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:146
 in setimageformat at /Users/zzz/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:328
 in getblob at /Users/zzz/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:208
 in writemime at /Users/zzz/.julia/v0.3/Images/src/io.jl:226
 in base64 at base64.jl:125
 in display_dict at /Users/zzz/.julia/v0.3/IJulia/src/execute_request.jl:32
```

This is on a fresh install of Images and Homebrew -- actually on a fresh install of the entire `.julia` directory tree. (I even tried the `Homebrew.rm("imagemagick")`, etc. reinstall.)

**Comment by timholy** [comment] 2015-09-21 18:11
That is really weird, because for me
```
julia> @which convert(Image, rand(3,5))
convert(::Type{Images.Image{T,N,A<:AbstractArray{T,N}}}, A::AbstractArray{T,N}) at /home/tim/.julia/v0.4/Images/src/core.jl:221
```
which, if you look at the source code, doesn't use ImageMagick at all!

Can you be a bit more explicit about how the error happens? Is it when you say `using Images`?

**Comment by ehkropf** [comment] 2015-09-22 07:23
I am `using Images`, but I tried it in a terminal instead of Jupyter, and it worked fine. (I did get the same result from `@which` as you.) Could it be that IJulia is asking for another `convert

**Comment by timholy** [comment] 2015-09-22 08:40
Ah, this helps a lot. What's happening is that IJulia is adding an extra step, trying to display the image for you, and that uses ImageMagick.

Glad you tried the whole Homebrew debugging. Here I'm a bit out of my element, since I've never used OSX. What does `BinDeps.debug("Images")` say?

If any of the experienced Images & OSX users can chime in, I'd be grateful.

**Comment by ehkropf** [comment] 2015-09-22 17:41
Strange. Now I'm getting a message about missing ImageMagick utilities:
```
julia> using Images
WARNING: ImageMagick utilities not found. Install for more file format support.

julia> using BinDeps

julia> BinDeps.debug("Images")
INFO: Reading build script...
ERROR: libwand not defined
 in anonymous at no file
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in debug_context at /Users/zzz/.julia/v0.3/BinDeps/src/debug.jl:54
 in debug at /Users/zzz/.julia/v0.3/BinDeps/src/debug.jl:59
 in debug at /Users/zzz/.julia/v0.3/BinDeps/src/debug.jl:65
while loading /Users/zzz/.julia/v0.3/Images/deps/build.jl, in expression starting on line 96
```
Strange I didn't see that yesterday. Embarrassing if it was, but unfortunately I'm not 100% sure it wasn't.

**Comment by timholy** [comment] 2015-09-22 21:50
How about `Pkg.build("Images")`?

**Comment by ehkropf** [comment] 2015-09-24 09:24
A `Pkg.build("Images")` fixed the warning on `using Images`. I must have knocked something out of place when trying various things.

To make sure I haven't caused anything else, the following is output based on a freshly created `~/.julia` directory tree.
```
julia> using BinDeps

julia> using Images

julia> BinDeps.debug("Images")
INFO: Reading build script...
ERROR: libwand not defined
 in anonymous at no file
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in debug_context at /Users/ehkropf/.julia/v0.3/BinDeps/src/debug.jl:54
 in debug at /Users/zzz/.julia/v0.3/BinDeps/src/debug.jl:59
 in debug at /Users/zzz/.julia/v0.3/BinDeps/src/debug.jl:65
while loading /Users/zzz/.julia/v0.3/Images/deps/build.jl, in expression starting on line 96
```

**Comment by timholy** [comment] 2015-09-24 10:24
Did it spit out any output right after the add?

Also a recently-discovered issue with `BinDeps.debug` might make this more confusing: https://github.com/JuliaLang/BinDeps.jl/pull/179

**Comment by ehkropf** [comment] 2015-09-24 16:51
It gave what I assume is the standard install output for the package. I didn't see any obvious warnings or errors. I can recreate it and paste it below if you think that would be informative.

**Comment by ehkropf** [comment] 2015-09-24 17:03
Though having re-run the whole install just for kicks, I noticed
```
==> Installing staticfloat/juliadeps/imagemagick
==> Downloading https://juliabottles.s3.amazonaws.com/imagemagick-6.8.9-1_1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring imagemagick-6.8.9-1_1.yosemite.bottle.tar.gz
🍺  /Users/zzz/.julia/v0.3/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1: 1436 files, 22M
To relink: brew unlink imagemagick && brew link imagemagick
```

A point of interest in reference to the `BinDeps.debug` issue: I did get the `ImageMagick utilities not found` as mentioned above after having done `using Images`, `using BinDeps`, `BinDeps.debug("Images")`, quit the Julia sell, restart, and then `using Images` again.

**Comment by timholy** [comment] 2015-09-24 17:55
If you do a `Pkg.build("Images")` as the very last step (*don't* call `BinDeps.debug` again!), then does everything work?

**Comment by ehkropf** [comment] 2015-09-25 09:04
Not much from the build output:
```
julia> Pkg.build("Images")
INFO: Building Homebrew
HEAD is now at 136cb22 librsvg: update 2.40.10_1 bottle.
HEAD is now at 1b584ee We definitely need gnome-icon-theme
INFO: Building Images

julia> 
```
I still get the original error.

I'll try to get it to use imagemagick via the REPL instead of IJulia to see if I can get the same error.

**Comment by timholy** [comment] 2015-09-25 13:19
Calling in the heavy artillery: @staticfloat.

**Comment by staticfloat** [comment] 2015-09-26 06:58
@ehkropf I seem to be having trouble getting IJulia to work with Julia 0.4-rc2 at the moment; is there a way I can try to reproduce your issues without using IJulia?

**Comment by staticfloat** [comment] 2015-09-26 07:06
Okay, nevermind, I got it working.  However, (and this may or may not have anything to do with the current issue) if I run the following:

```julia
using Images
const ϕ = golden

function foo(z)
  c = (φ-2)+(φ-1)im
  max = 80
  for n = 1:max
    abs(z) ≥ 2 && return n-1
    z = z^2 + c
  end
  return max
end

# Let's apply foo to a grid of numbers.
foo(x, y) = foo(x + y*im)
foo_grid(n) =
  broadcast(foo,
            linspace(-0.5, 1, n)',
            linspace(-1, 0.5, n))

# Let's try it as an image:
convert(Image, scale(foo_grid(500), 1/80))
```

I do not get the inline image I was expecting.  Instead, I get the following output:
```
Gray Images.Image with:
  data: 500x500 Array{Float64,2}
  properties:
    timedim: 0
    colorspace: Gray
    colordim: 0
    spatialorder:  y x
    pixelspacing:  1.0 1.0
```

Has something changed since the 6 months ago I first wrote this test script, or is something broken?

**Comment by timholy** [comment] 2015-09-26 11:30
My IJulia is broken right now, but does it help to type `display(img)`? (where `img` is the result of the `convert` function)

**Comment by staticfloat** [comment] 2015-09-26 15:23
Nope, it still just prints out the text.

**Comment by timholy** [comment] 2015-09-26 18:45
Try `writemime(STDOUT, "image/png", img)`?

**Comment by staticfloat** [comment] 2015-09-26 20:04
That gives me:
```
LoadError: MethodError: `writemime` has no method matching writemime(::Base.PipeEndpoint, ::MIME{symbol("image/png")}, ::Images.Image{Float64,2,Array{Float64,2}})
Closest candidates are:
  writemime(::IO, !Matched::AbstractString, ::Any)
  writemime(::IO, !Matched::MIME{symbol("text/plain")}, ::Images.AbstractImageDirect{T,N})
  writemime(::IO, !Matched::MIME{symbol("text/csv")}, ::Union{AbstractArray{T,1},AbstractArray{T,2}})
  ...
while loading In[1], in expression starting on line 33
 in writemime at multimedia.jl:43
```

**Comment by timholy** [comment] 2015-09-26 20:15
Weird; why isn't that covered by https://github.com/timholy/Images.jl/blob/818fbc63fdcb6442150815dca7217db89c84650d/src/io.jl#L207-L210?

**Comment by staticfloat** [comment] 2015-09-26 23:46
Oh phooey, I was stuck on an old branch, so `Pkg.update()` was never doing anything, and `io.jl` wasn't being included on that old commit.  ALRIGHT WE ARE BACK IN BUSINESS.  @ehkropf I can successfully run the following snippet and get an image out:

```julia
using Images

# Beautiful snowflakes
const ϕ = golden
function foo(z)
  c = (φ-2)+(φ-1)im
  max = 80
  for n = 1:max
    abs(z) ≥ 2 && return n-1
    z = z^2 + c
  end
  return max
end

# Let's define foo over the complex plane, then create an n-by-n grid, sampling foo at each point
foo(x, y) = foo(x + y*im)
foo_grid(n) = broadcast(foo, linspace(-0.5, 1, n)', linspace(-1, 0.5, n))

# Let's display it as an image, (scaled so that it converts nicely)
data = foo_grid(200)/80
display(typeof(data))
img = convert(Image, data)
```
<img width="669" alt="screen shot 2015-09-26 at 4 26 09 pm" src="https://cloud.githubusercontent.com/assets/130920/10120346/594ec716-646b-11e5-8d5d-3c331cfc3ee4.png">

Note that it is an `Array{Float64,2}`, so there is definitely a case for this working on OSX, we just have to figure out what is going wrong.  Can you run [this little script](https://gist.github.com/staticfloat/88f16a7cb83d644739c8) (example output is included in that gist) inside of your IJulia session and post the output?

**Comment by alanedelman** [comment] 2015-09-30 12:16
I tried the code
```
using Images

# Beautiful snowflakes
const ϕ = golden
function foo(z)
  c = (φ-2)+(φ-1)im
  max = 80
  for n = 1:max
    abs(z) ≥ 2 && return n-1
    z = z^2 + c
  end
  return max
end

# Let's define foo over the complex plane, then create an n-by-n grid, sampling foo at each point
foo(x, y) = foo(x + y*im)
foo_grid(n) = broadcast(foo, linspace(-0.5, 1, n)', linspace(-1, 0.5, n))

# Let's display it as an image, (scaled so that it converts nicely)
data = foo_grid(200)/80
display(typeof(data))
img = convert(Image, data)
```

and got
```
Array{Float64,2}
UnableToOpenConfigureFile `coder.xml' @ warning/configure.c/GetConfigureOptions/706

 in error at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in error at /Users/alanedelman/.julia/v0.4/Images/src/ioformats/libmagickwand.jl:146
 in setimageformat at /Users/alanedelman/.julia/v0.4/Images/src/ioformats/libmagickwand.jl:328
 in getblob at /Users/alanedelman/.julia/v0.4/Images/src/ioformats/libmagickwand.jl:208
 in writemime at /Users/alanedelman/.julia/v0.4/Images/src/io.jl:226
 in base64encode at base64.jl:160
 in display_dict at /Users/alanedelman/.julia/v0.4/IJulia/src/execute_request.jl:32
```

I did a pkg.update() with no success.

@stevengj    There is a hw i'm giving to the graduate class but I fear disaster.
Anything I can do to make this work?  
(See https://github.com/alanedelman/18.337_2015/blob/master/HW2%20Due%20Tuesday%20October%2013th.ipynb )

**Comment by stevengj** [comment] 2015-09-30 12:54
@alanedelman, wasn't this the same problem that you were having on your computer last week?  I didn't have time to track it down, but recall that I fixed it by downgrading Images to an older version.

**Comment by alanedelman** [comment] 2015-09-30 13:37
YES, it is the same issue, but the fix was fragile.  It worked for a while, and stopped working.
Never worked in 0.4.   .... and fixing for me on one laptop is very different for  a fix for a classroom
setting :-)

**Comment by SimonDanisch** [comment] 2015-09-30 13:56
ImageMagick is amazingly fragile and hard to set up... I hope I can invest
some time in the next months to make it more stable and offer better
fallbacks for it. See JuliaIO/ImageMagick.jl#7. It was quite a journey to
get it to build on all test machines without problems and i'm pretty sure
that it's still not set up properly.

**Comment by stevengj** [comment] 2015-09-30 14:10
The point is that if it was fixed, even temporarily, on Alan's machine by a downgrade of Images.jl, that suggests to me that it may not be a configuration problem of ImageMagick but rather a bug that was introduced into Images at some point.   Someone should try to do a `git bisect` on Images.jl.

**Comment by alanedelman** [comment] 2015-09-30 14:22
How do i try previous versions of Images again?

I tried
```
Pkg.checkout("Images", "v0.4.47")
```
and got
```

INFO: Checking out Images v0.4.47...
fatal: Cannot update paths and switch to branch 'v0.4.47' at the same time.
Did you intend to checkout 'origin/v0.4.47' which can not be resolved as commit?
```

```
LoadError: failed process: Process(`git --work-tree=/Users/alanedelman/.julia/v0.4/Images --git-dir=/Users/alanedelman/.julia/v0.4/Images/.git checkout -q -B v0.4.47 -t origin/v0.4.47`, ProcessExited(128)) [128]
while loading In[9], in expression starting on line 2
```

**Comment by timholy** [comment] 2015-09-30 15:17
I'm hoping to tag a new version of Images soon that changes its whole relationship with ImageMagick. Would you care to try the master version now and see how it works?

**Comment by alanedelman** [comment] 2015-09-30 15:40
it started to work and then broke again
trying to isolate the issue... but may have to get to it later

**Comment by ehkropf** [comment] 2015-09-30 17:05
@staticfloat Tried running your debug script. I don't seem to be able to call `Sys.Libdl.dllist()`. In fact,
```
julia> Sys.Libdl.dllist()
ERROR: Libdl not defined
```
Is that documented somewhere?

Having commented out the `dllist()` part, here is the output from the rest:
```
-----------------------------------------------------------
MAGICK Environment variables:
-----------------------------------------------------------

-----------------------------------------------------------
BinDeps.debug() output: (note, this can fail!)
-----------------------------------------------------------
INFO: Reading build script...
The package declares 1 dependencies.
 - Library "libwand"
    - Satisfied by:
      - Homebrew Bottles imagemagick at /Users/ehkropf/.julia/v0.3/Homebrew/deps/usr/lib/libMagickWand-6.Q16.dylib
    - Providers:
      - Homebrew Bottles imagemagick

-----------------------------------------------------------
Pkg.build() output:
-----------------------------------------------------------
INFO: Building Homebrew
From https://github.com/Homebrew/homebrew
   8a12b99..88eaeec  master     -> origin/master
HEAD is now at 88eaeec fish: fix head compile
HEAD is now at b359d09 gnome-icon-theme needs to be mirrored by us to avoid pkg-config problems
INFO: Building Images
```

**Comment by staticfloat** [comment] 2015-09-30 17:15
@ehkropf Ah, you must be on Julia v0.3.  Try removing the `Libdl.` part, so that it's just `Sys.dllist()`.

**Comment by staticfloat** [comment] 2015-09-30 17:43
Actually, I've updated the script to give a little bit more information, could you download the new script and run it again?  @alanedelman your output would also be useful, thanks.

**Comment by staticfloat** [comment] 2015-09-30 17:44
@alanedelman it would also be helpful to us if you could run [this script](https://gist.github.com/staticfloat/88f16a7cb83d644739c8) so that we can figure out what's going on in your machine.

**Comment by staticfloat** [comment] 2015-09-30 17:53
Oh, also, it looks like the build system for `Images` is undergoing an overhaul right now, you may want to try `Pkg.checkout("Images")` to see if that fixes things for you.

**Comment by alanedelman** [comment] 2015-09-30 22:31
I get
```
-----------------------------------------------------------
LoadError: MethodError: `start` has no method matching start(::Symbol)
while loading In[1], in expression starting on line 10

 in writemime at /Users/alanedelman/.julia/v0.4/FileIO/src/FileIO.jl:105
 in sprint at iostream.jl:211
 in display_dict at /Users/alanedelman/.julia/v0.4/IJulia/src/execute_request.jl:29
 in display at /Users/alanedelman/.julia/v0.4/IJulia/src/inline.jl:35
 [inlined code] from multimedia.jl:151
 in display at multimedia.jl:162

All loaded libwands:
-----------------------------------------------------------
```

whether i use `imread` or `load` I see this start issue

**Comment by staticfloat** [comment] 2015-09-30 23:46
@alanedelman That's..... weird.  Have you edited your `Images` install at all?  What does `Pkg.status()` say?

**Comment by lucasb-eyer** [comment] 2015-10-01 08:49
That's weird because the backtrace points to [`writemime`](https://github.com/JuliaIO/FileIO.jl/blob/7da378db89401a0c5f1d80ca6b40d0075b3b55fa/src/FileIO.jl#L105). Specifically, it seems to be a consquence of [`applicable_mime`](https://github.com/JuliaIO/FileIO.jl/blob/fd6e1e8bc4fce88eb1c5a381ca41d57f8a1e2934/src/loadsave.jl#L21) returning the symbol `:nothing` when it doesn't find a handler. I wonder what `::MIME` it's trying to write? Maybe you're missing the `ImageMagick` package for some reason?

**Comment by SimonDanisch** [comment] 2015-10-01 09:41
That's pretty likely.
See JuliaIO/FileIO.jl#42

**Comment by alanedelman** [comment] 2015-10-01 11:15
Progress!  I can make it part of the way through my notebook now.  Thank you.
More later.

**Comment by ehkropf** [comment] 2015-10-02 14:38
Being aware of the amount of unhelpfulness contained, I'll share the following information.

My error went away, and image display in IJulia is working now after I
* Updated OS X to El Capitan,
* updated the julia kernel used to 0.4.0-rc3,
* updated python from 2.7 to 3.4, and
* removed a macports ImageMagick install.
Guessing, I would say it was one of the last three. I'll try later installing the macports ImageMagick to see if it breaks things again.

**Comment by alanedelman** [comment] 2015-10-02 20:04
Okay, we found the problem.  `Pkg.build` creates a `deps.jl` file with an `__init__` function that sets several environment variables, but `Images.jl` never actually includes `deps.jl`.  Just adding this to the top of Images.jl fixes the problem:
```jl
const depfile = joinpath(dirname(@__FILE__), "..", "deps", "deps.jl")
isfile(depfile) || error("Images not properly installed. Please run Pkg.build(\"Images\")")
include(depfile) # generated by Pkg.build("Images")
```

**Comment by timholy** [comment] 2015-10-02 21:57
Can you paste the contents of your `deps.jl` file, and also let me know which `sha` of Images you're on? That stuff has been changing a lot lately in response to package precompilation.

In particular, if you're on 0.4.48, I _think_ all the stuff in `deps.jl` is intended for configuring ImageMagick, and I believe it should be included in `src/ioformats/libmagickwand.jl`. So this puzzles me.

**Comment by stevengj** [comment] 2015-10-02 22:21
(Alan, `cd ~/.julia/v0.4/Images` and run `git rev-parse HEAD` to get the sha, and `cat deps/deps.jl` to get the contests of `deps.jl`.)

**Comment by alanedelman** [comment] 2015-10-02 22:33
Here goes
```
# This is an auto-generated file; do not edit

# Pre-hooks

# Macro to load a library
macro checked_lib(libname, path)
    ((VERSION >= v"0.4.0-dev+3844" ? Base.Libdl.dlopen_e : Base.dlopen_e)(path) == C_NULL) && error("Unable to load \n\n$libname ($path)\n\nPlease re-run Pkg.build(package), and restart Julia.")
    quote const $(esc(libname)) = $path end
end

# Load dependencies
@checked_lib libwand "/Users/alanedelman/.julia/v0.4/Homebrew/deps/usr/lib/libMagickWand-6.Q16.dylib"

# Load-hooks
function __init__()
    ENV["MAGICK_CONFIGURE_PATH"] = joinpath("/Users/alanedelman/.julia/v0.4/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1","lib","ImageMagick","config-Q16")
    ENV["MAGICK_CODER_MODULE_PATH"] = joinpath("/Users/alanedelman/.julia/v0.4/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1", "lib","ImageMagick","modules-Q16","coders")
    ENV["PATH"] = joinpath("/Users/alanedelman/.julia/v0.4/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1", "bin") * ":" * ENV["PATH"]
    ccall((:MagickWandGenesis,libwand), Void, ())
end
```

**Comment by alanedelman** [comment] 2015-10-02 22:34
oh and 
```
ecd35f185912489a94e57f22852d8be974b6a9dd
```

**Comment by timholy** [comment] 2015-10-03 08:41
Yes, so it was like I guessed: all of the stuff in `deps.jl` is for ImageMagick, and it should be included in `src/ioformats/libmagickwand.jl`. Consequently, I don't understand why you were able to fix the problem by including it in Images.jl, too. If anything, by including it in `libmagickwand.jl` (which defines its own internal module in Images), the `__init__` function will run earlier, because the internal module "closes" earlier than the outer `Images` module.

Anyone have an explanation?

**Comment by lucasb-eyer** [comment] 2015-10-03 10:24
Is it possible that [this line](https://github.com/timholy/Images.jl/blob/ecd35f185912489a94e57f22852d8be974b6a9dd/src/Images.jl#L41) only ran during the build step because of pre-compilation? Otherwise, Alan either must have seen [this error message](https://github.com/timholy/Images.jl/blob/ecd35f185912489a94e57f22852d8be974b6a9dd/src/ioformats/libmagickwand.jl#L31) or `deps.jl` must have been included. Mind you, I'm talking out of my ass here, I have no clue how pre-compilation actually works.

**Comment by stevengj** [comment] 2015-10-03 12:19
@timholy, `libmagickwand.jl` defines its own `__init__` function.  That will overwrite the one in `deps.jl`, so the `__init__` function in `deps.jl` will never be called.

**Comment by timholy** [comment] 2015-10-03 14:33
This was fixed in #366, I just needed to tag a new release. Sorry about that.

**Comment by timholy** [comment] 2015-10-03 14:33
(Fixed if you do `Pkg.update()`.)

**Comment by stevengj** [comment] 2015-10-03 14:34
Alan, you'll want to do:
```
cd ~/.julia/v0.4/Images
git reset --hard
```
and then do `Pkg.update()`.

**Closed** 2015-10-03 14:33 UTC

**Comment by alanedelman** [comment] 2015-10-03 14:43
so let me get this straight

for the students starting today it's enough to do
```
Pkg.add("Images")
using Images
```
but for those who may have tried and failed to date they should do
```
Pkg.update()
using Images 
```

**Comment by stevengj** [comment] 2015-10-03 15:18
Yes.

**Comment by alanedelman** [comment] 2015-10-03 22:04
Thanks.  We can now have our speed contest :-)
http://localhost:8890/notebooks/HW2%20Due%20Tuesday%20October%2013th.ipynb

Everyone is welcome to participate, not just the students at MIT :-)

**Comment by timholy** [comment] 2015-10-03 23:17
But not everyone has access to a resource that contains `localhost` into the URL :smile:.

**Comment by alanedelman** [comment] 2015-10-03 23:21
https://github.com/alanedelman/18.337_2015/blob/master/HW2%20Due%20Tuesday%20October%2013th.ipynb

:-)
