### ISSUE TITLE
Pkg.add("Images") and 'using Images ' fails - error 404 for ImageMagick-6.9.0-0-Q16-x64-dll.exe 

### ISSUE THREAD

**Issue by petr-ujezdsky** [timholy/Images.jl#244] opened 2015-01-07 14:21 UTC
You are trying to download file

ImageMagick-6.9.0-0-Q16-x64-dll.exe

which does not exist anymore. Unfortunately, it creates this file with text content '<html>....error 404...</html>'.
I have downloaded newer version 'ImageMagick-6.9.0-3-Q16-x64-dll.exe', renamed to the 6.9.0-0 and everything is fine now.

Please update install scripts to newer version.

**Comment by timholy** [comment] 2015-01-07 15:52
Already done; see #242. We just need to bump the version of Images (am trying to fix #243 first). But, you can always check out the latest master with `Pkg.checkout("Images")`.

FYI, you did a great job of debugging this. Even better would be to submit a pull request! (That would have been redundant this time, of course; it's always best to check the commit history first.)

**Comment by petr-ujezdsky** [comment] 2015-01-07 16:17
I wanted to make a pull request after filing this report, but found out it is already fixed :)
Strange thing is, that you fixed it around 02:00 and I have downloaded Juno+Julia around 15:00. Git repo in ~\.julia\v0.3\Images still contained old code - oddly it was not updated to the newest commit.

Thanks for quick response. I am new to git and Julia (+ Juno).

**Comment by timholy** [comment] 2015-01-07 16:47
There's a lot to learn, so no sweat. Here's the issue: when you say `Pkg.add("Images")`, it downloads a "tagged" version, one that I (or someone else) has "certified" as being a good release. This is an effort to shield users from random bugs that appear on the master branch (which is what you get from `Pkg.checkout("Images")`); hard-core users will often run master (because they need the latest-and-greatest, and often contribute to Images). So the hard-core basically act as a beta-testing audience.

The problem is, when bugs are fixed, they don't become available to general users until someone remembers to tag a new release. That doesn't always happen as often as it should (which is my fault).

**Comment by timholy** [comment] 2015-01-19 03:03
Should be fixed now.

**Closed by timholy** 2015-01-19 03:03 UTC
