### ISSUE TITLE
ERROR: Images had test errors

### ISSUE THREAD

**Issue by nikolaypavlov** [timholy/Images.jl#344] opened 2015-08-25 17:46 UTC
I'm getting this error during Pkg.test:
```
Algorithms: .................................................................................E..................................
  Error :: (line:505)
    Expression: Images.imfilter(Aimg,kern) --> roughly(permutedims(Af,[3,1,2]))
    `-` has no method matching -(::Array{Float64,3}, ::Image{Float64,3,Array{Float64,3}})
     in anonymous at no file:34
     in anonymous at /Users/quetzal/.julia/v0.3/FactCheck/src/FactCheck.jl:263
     in anonymous at /Users/quetzal/.julia/v0.3/FactCheck/src/FactCheck.jl:271
     in do_fact at /Users/quetzal/.julia/v0.3/FactCheck/src/FactCheck.jl:333
     in anonymous at /Users/quetzal/.julia/v0.3/Images/test/algorithms.jl:271
     in context at /Users/quetzal/.julia/v0.3/FactCheck/src/FactCheck.jl:474
     in anonymous at /Users/quetzal/.julia/v0.3/Images/test/algorithms.jl:135
     in facts at /Users/quetzal/.julia/v0.3/FactCheck/src/FactCheck.jl:448
     in include at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
     in include_from_node1 at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
     in include at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
     in include_from_node1 at loading.jl:128
     in process_options at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
     in _start at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
Edge: ..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
ERROR: FactCheck finished with 1 non-successful tests.
 in error at error.jl:21
 in exitstatus at /Users/quetzal/.julia/v0.3/FactCheck/src/FactCheck.jl:563
 in include at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
while loading /Users/quetzal/.julia/v0.3/Images/test/runtests.jl, in expression starting on line 30
```
See below my julia environment details: 
```
quetzal@MacBook-Pro:~ $ julia -E 'versioninfo()' 
Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
nothing
```

I'm using Images v0.4.45.

**Comment by mattcbro** [comment] 2015-08-25 19:13
I also am getting errors when running Pkg.test("Images"),  namely

  Error :: (line:-1)
    Expression: props[key] --> anything
    anything not defined
     in anonymous at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:259
     in anonymous at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:271
     in do_fact at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:333
     in anonymous at /home/matthew/.julia/v0.3/Images/test/readremote.jl:271
     in context at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:474
     in anonymous at /home/matthew/.julia/v0.3/Images/test/readremote.jl:189
     in facts at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:448
     in include at ./boot.jl:245
     in include_from_node1 at ./loading.jl:128
     in include at ./boot.jl:245
     in include_from_node1 at loading.jl:128
     in process_options at ./client.jl:285
     in _start at ./client.jl:354

and additionally
  Error :: (line:-1)
    Expression: props[key] --> anything
    anything not defined
     in anonymous at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:259
     in anonymous at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:271
     in do_fact at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:333
     in anonymous at /home/matthew/.julia/v0.3/Images/test/readremote.jl:271
     in context at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:474
     in anonymous at /home/matthew/.julia/v0.3/Images/test/readremote.jl:189
     in facts at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:448
     in include at ./boot.jl:245
     in include_from_node1 at ./loading.jl:128
     in include at ./boot.jl:245
     in include_from_node1 at loading.jl:128
     in process_options at ./client.jl:285
     in _start at ./client.jl:354

**Comment by mattcbro** [comment] 2015-08-25 19:21
Oh one other thing possibly related is that I'm getting a lot of these warnings:
WARNING: Color is deprecated, please use Colors instead.

**Comment by kmsquire** [comment] 2015-08-25 21:00
Looks like you need to update Images.jl, at the least.

**Comment by timholy** [comment] 2015-08-25 21:00
If you're seeing `WARNING: Color is deprecated, please use Colors instead`, then that means you have local modifications of some package that is preventing you from upgrading to the latest versions of packages that Images depends on. Check `Pkg.status()` for anything marked "dirty" and try to resolve the issue.

**Comment by nikolaypavlov** [comment] 2015-08-25 21:56
@mattcbro just remove Color with `Pkg.rm("Color")` and install Colors instead... 
BTW it didn't help me to fix the failed test...

**Comment by timholy** [comment] 2015-08-26 02:04
For the PyPlot error, a new version just got tagged 3 hours ago. `Pkg.update()` might fix it.

@nikolaypavlov, does this not work for you? (From a fresh REPL session)
```jl
julia> using Images

julia> A = rand(5,7,6);

julia> img = grayim(A)
Gray Images.Image with:
  data: 5x7x6 Array{Float64,3}
  properties:
    colorspace: Gray
    spatialorder:  x y z

julia> A-img
5x7x6 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
...
```
If that works, then the error message makes little sense because the operation it is complaining about is defined.

Are you using any other packages simultaneously? DataArrays, for example?

**Comment by timholy** [comment] 2015-08-26 02:14
@mattcbro, `anything` was defined in FactCheck but was recently deleted. https://github.com/JuliaLang/FactCheck.jl/commit/57e4d5b48fabaefa1e7d6b06af400b02c1e05700

**Comment by timholy** [comment] 2015-08-26 02:21
In general, if the error messages are different, please open a separate issue. Once #344 merges, it will close this issue automatically. Hopefully we'll have @nikolaypavlov's error resolved anyway.

**Comment by nikolaypavlov** [comment] 2015-08-26 14:23
@timholy It doesn't work for me. (I'm using plain julia REPL session): 
```
julia> A-img
ERROR: `-` has no method matching -(::Array{Float64,3}, ::Image{Float64,3,Array{Float64,3}})
```
Here is my `Pkg.status()` as well:
```
julia> Pkg.status()
29 required packages:
 - ArgParse                      0.2.11
 - Bokeh                         0.1.0
 - Cairo                         0.2.29
 - Clustering                    0.4.0
 - DSP                           0.0.10
 - DataFrames                    0.6.9
 - DecisionTree                  0.3.9
 - Distance                      0.5.1
 - Gadfly                        0.3.14
 - HDF5                          0.5.5
 - HTTPClient                    0.1.5
 - HypothesisTests               0.2.9
 - IJulia                        0.2.5
 - Images                        0.4.45
 - JSON                          0.4.5
 - Jewel                         1.0.5
 - JuMP                          0.9.3
 - KernelDensity                 0.1.1
 - KernelEstimator               0.1.4
 - Lint                          0.1.68
 - Loess                         0.0.3
 - MLBase                        0.5.1
 - MachineLearning               0.0.3
 - Mocha                         0.0.9+             master
 - MultivariateStats             0.2.1
 - NumericExtensions             0.6.2
 - PyPlot                        2.0.0
 - RDatasets                     0.1.2
 - Winston                       0.11.12
67 additional packages:
 - ArrayViews                    0.6.3
 - BinDeps                       0.3.15
 - Blosc                         0.1.4
 - Calculus                      0.1.10
 - Codecs                        0.1.4
 - ColorTypes                    0.1.3
 - ColorVectorSpace              0.0.2
 - Colors                        0.5.2
 - Compat                        0.6.0
 - Compose                       0.3.14
 - Contour                       0.0.7
 - Cubature                      1.0.7
 - DataArrays                    0.2.17
 - DataStructures                0.3.12
 - Dates                         0.3.2
 - Devectorize                   0.4.1
 - Distances                     0.2.0
 - Distributions                 0.8.3
 - Docile                        0.5.16
 - DualNumbers                   0.1.3
 - FactCheck                     0.4.0
 - FixedPointNumbers             0.0.10
 - GZip                          0.2.17
 - Graphics                      0.1.0
 - Grid                          0.3.10
 - Hexagons                      0.0.3
 - Homebrew                      0.1.16
 - ImmutableArrays               0.0.10
 - IniFile                       0.2.4
 - Iterators                     0.1.8
 - JLD                           0.5.4
 - JuliaParser                   0.6.2
 - LNR                           0.0.1
 - LaTeXStrings                  0.1.4
 - Lazy                          0.10.0
 - LibCURL                       0.1.4
 - Logging                       0.1.1
 - MacroTools                    0.2.0
 - MathProgBase                  0.3.16
 - Mustache                      0.0.11
 - NaNMath                       0.1.0
 - Nettle                        0.1.10
 - NumericFuns                   0.2.3
 - Optim                         0.4.2
 - Options                       0.2.4
 - PDMats                        0.3.5
 - Polynomials                   0.0.3
 - PowerSeries                   0.1.13
 - PyCall                        0.8.2
 - REPLCompletions               0.0.3
 - Reexport                      0.0.2
 - Requires                      0.1.3
 - ReverseDiffSparse             0.2.10
 - Roots                         0.1.16
 - SHA                           0.1.1
 - SIUnits                       0.0.5
 - Showoff                       0.0.4
 - SortingAlgorithms             0.0.5
 - StatsBase                     0.7.1
 - StatsFuns                     0.1.2
 - TexExtensions                 0.0.2
 - TextWrap                      0.1.3
 - Tk                            0.3.5
 - URIParser                     0.0.5
 - WoodburyMatrices              0.1.1
 - ZMQ                           0.2.0
 - Zlib                          0.1.8
```

**Comment by rsrock** [comment] 2015-08-26 15:02
I can confirm this on Julia 0.3.11.  No problem on Julia 0.4

**Comment by rsrock** [comment] 2015-08-26 15:30
I'm a bit stumped, I don't see anything obvious that would cause this problem.  Issue appears at 8917723 in Travis.

I've ruled this out for this particular issue, but FYI there seems to be an issue with `ColorVectorSpace` on Julia 0.3.  After a `Pkg.update()`, I don't see it in my package dir even though `Images` lists it as a requirement.  Does `ColorVectorSpace` need to be tagged or something?  Also, is it "0.3-clean"?

**Comment by mattcbro** [comment] 2015-08-26 17:41
After today's update (08/24/2015) the Color vs Colors package warnings are gone from the PyPlot module as advertised.  Pkg.test("Images") still fails with some slightly different error messages than before.

The anything not defined error still occurs in FactCheck.jl line 259 .   However now in the algorithm section we have,

Algorithms: .................................................................................E..................................
  Error :: (line:-1)
    Expression: Images.imfilter(Aimg,kern) --> roughly(permutedims(Af,[3,1,2]))
    `-` has no method matching -(::Array{Float64,3}, ::Image{Float64,3,Array{Float64,3}})
     in anonymous at no file:34
     in anonymous at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:263
     in anonymous at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:271
     in do_fact at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:333
     in anonymous at /home/matthew/.julia/v0.3/Images/test/algorithms.jl:271
     in context at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:474
     in anonymous at /home/matthew/.julia/v0.3/Images/test/algorithms.jl:135
     in facts at /home/matthew/.julia/v0.3/FactCheck/src/FactCheck.jl:448
     in include at ./boot.jl:245
     in include_from_node1 at ./loading.jl:128
     in include at ./boot.jl:245
     in include_from_node1 at loading.jl:128
     in process_options at ./client.jl:285
     in _start at ./client.jl:354
So a problem with how imfilter() is being used.  After a Pkg.update() of my 0.3.11 julia installation, Pkg.status() yields:
16 required packages:
 - Autoreload                    0.2.0+             master
 - CPLEX                         0.0.15
 - Clp                           0.0.10
 - DataFrames                    0.6.9
 - Debug                         0.1.4
 - GLPK                          0.2.16
 - GLPKMathProgInterface         0.1.13
 - Gadfly                        0.3.14
 - Gurobi                        0.1.29
 - IJulia                        0.2.5
 - Images                        0.4.45
 - Ipopt                         0.1.16
 - Jewel                         1.0.5
 - MAT                           0.2.12
 - MathProgBase                  0.3.16
 - PyPlot                        2.0.1
55 additional packages:
 - ArrayViews                    0.6.3
 - BinDeps                       0.3.15
 - Blosc                         0.1.4
 - Calculus                      0.1.10
 - Cbc                           0.1.7
 - Codecs                        0.1.4
 - ColorTypes                    0.1.3
 - ColorVectorSpace              0.0.2
 - Colors                        0.5.2
 - Compat                        0.6.0
 - Compose                       0.3.14
 - Contour                       0.0.7
 - DataArrays                    0.2.17
 - DataStructures                0.3.12
 - Dates                         0.3.2
 - Distances                     0.2.0
 - Distributions                 0.8.3
 - Docile                        0.5.16
 - DualNumbers                   0.1.3
 - FactCheck                     0.4.0
 - FixedPointNumbers             0.0.10
 - GZip                          0.2.17
 - Graphics                      0.1.0
 - Grid                          0.3.10
 - HDF5                          0.5.5
 - Hexagons                      0.0.3
 - ImmutableArrays               0.0.10
 - Iterators                     0.1.8
 - JSON                          0.4.5
 - JuliaParser                   0.6.2
 - KernelDensity                 0.1.1
 - LNR                           0.0.1
 - LaTeXStrings                  0.1.4
 - Lazy                          0.10.0
 - Loess                         0.0.3
 - MacroTools                    0.2.0
 - NaNMath                       0.1.0
 - Nettle                        0.1.10
 - Optim                         0.4.2
 - PDMats                        0.3.5
 - PyCall                        0.8.2
 - REPLCompletions               0.0.3
 - Reexport                      0.0.2
 - Requires                      0.1.3
 - SHA                           0.1.1
 - SIUnits                       0.0.5
 - Showoff                       0.0.4
 - SortingAlgorithms             0.0.5
 - StatsBase                     0.7.1
 - StatsFuns                     0.1.2
 - TexExtensions                 0.0.2
 - URIParser                     0.0.5
 - WoodburyMatrices              0.1.1
 - ZMQ                           0.2.0
 - Zlib                          0.1.8

Hope that helps.

**Comment by timholy** [comment] 2015-08-26 19:20
This is really puzzling. Until late yesterday, we had 3 passes in a row on Travis, then it failed with the same error reported here:
https://travis-ci.org/timholy/Images.jl/builds

**Comment by timholy** [comment] 2015-08-26 20:08
OK, fixed (I hope). `Pkg.checkout("Images")` to test.

**Closed** 2015-08-26 20:07 UTC

**Comment by timholy** [comment] 2015-08-26 20:11
> I've ruled this out for this particular issue, but FYI there seems to be an issue with ColorVectorSpace on Julia 0.3. After a Pkg.update(), I don't see it in my package dir even though Images lists it as a requirement. Does ColorVectorSpace need to be tagged or something? Also, is it "0.3-clean"?

Seems OK:
```
$ JULIA_PKGDIR=/tmp/pkgs julia-old -q
julia> versioninfo()
Julia Version 0.3.12-pre+3
Commit 1b838a4* (2015-08-16 05:51 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU       L 640  @ 2.13GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.init()
INFO: Initializing package repository /tmp/pkgs/v0.3
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl

julia> Pkg.add("Images")
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of ColorTypes from git://github.com/JuliaGraphics/ColorTypes.jl.git
INFO: Cloning cache of ColorVectorSpace from git://github.com/JuliaGraphics/ColorVectorSpace.jl.git
INFO: Cloning cache of Colors from git://github.com/JuliaGraphics/Colors.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Docile from git://github.com/MichaelHatherly/Docile.jl.git
INFO: Cloning cache of FixedPointNumbers from git://github.com/JeffBezanson/FixedPointNumbers.jl.git
INFO: Cloning cache of Graphics from git://github.com/JuliaLang/Graphics.jl.git
INFO: Cloning cache of Images from git://github.com/timholy/Images.jl.git
INFO: Cloning cache of Reexport from git://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of SIUnits from git://github.com/Keno/SIUnits.jl.git
INFO: Cloning cache of TexExtensions from git://github.com/Keno/TexExtensions.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of Zlib from git://github.com/dcjones/Zlib.jl.git
INFO: Installing BinDeps v0.3.15
INFO: Installing ColorTypes v0.1.3
INFO: Installing ColorVectorSpace v0.0.2
INFO: Installing Colors v0.5.2
INFO: Installing Compat v0.6.0
INFO: Installing Docile v0.5.16
INFO: Installing FixedPointNumbers v0.0.10
INFO: Installing Graphics v0.1.0
INFO: Installing Images v0.4.45
INFO: Installing Reexport v0.0.2
INFO: Installing SHA v0.1.1
INFO: Installing SIUnits v0.0.5
INFO: Installing TexExtensions v0.0.2
INFO: Installing URIParser v0.0.5
INFO: Installing Zlib v0.1.8
INFO: Building Images
INFO: Package database updated

julia> Pkg.test("ColorVectorSpace")
INFO: Computing test dependencies for ColorVectorSpace...
INFO: Cloning cache of FactCheck from git://github.com/JuliaLang/FactCheck.jl.git
INFO: Installing FactCheck v0.4.0
INFO: Testing ColorVectorSpace
Colortypes
  > Arithmetic with Gray
  > Arithmetic with GrayA
  > Arithemtic with RGB
  > Arithemtic with RGBA
213 facts verified.
INFO: ColorVectorSpace tests passed
INFO: Removing FactCheck v0.4.0

julia> 
```

**Comment by nikolaypavlov** [comment] 2015-08-26 21:59
Fixed... Thanks.
