### ISSUE TITLE
reconstruct 

### ISSUE THREAD

**Issue by simplyman1** [timholy/Images.jl#300] opened 2015-05-05 21:31 UTC
How could I reconstruct the image using k largest singular values, where k is 5% , 10% , 25%, 35%, 50%, ,70% of picture's smaller dimension

**Comment by lucasb-eyer** [comment] 2015-05-05 21:41
Closing as duplicate of #286 where I pointed out the `svd` function.

For how exactly to perform reconstruction, you'll likely find it in some image processing/computer vision book or lecture notes. Further discussing this is out of scope for this issue tracker, which is mainly concerned about concrete problems with `Images.jl`'s library code.

**Closed by lucasb-eyer** 2015-05-05 21:41 UTC
