### ISSUE TITLE
Pkg.add("Images") Windows 7 64bit - "type Nothing has no field match"

### ISSUE THREAD

**Issue by ActionPace** [timholy/Images.jl#331] opened 2015-08-11 22:45 UTC
I can't install Images on a fresh install of Julia on Windows 7 - 64bit

Please advise, thanks

julia> Pkg.add("Images")
INFO: Installing Images v0.4.42
INFO: Installing SIUnits v0.0.5
INFO: Installing TexExtensions v0.0.2
INFO: Building Images
===============================[ ERROR: Images ]================================

type Nothing has no field match
while loading C:\Users\David\.julia\v0.3\Images\deps\build.jl, in expression sta
rting on line 37

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Images had build errors.

 - packages with build errors remain installed in C:\Users\David\.julia\v0.3
 - build the package(s) and all dependencies with `Pkg.build("Images")`
 - build a single package by running its `deps/build.jl` script

================================================================================

INFO: Package database updated

julia>

**Comment by postoroniy** [comment] 2015-08-12 01:01
Possible fix in builds.jl is
    pattern = "ImageMagick-6.9.*-Q16-$(OS_ARCH)-dll.exe"
at line 35
instead of 
    pattern = ">ImageMagick-6.9.*-Q16-$(OS_ARCH)-dll.exe"

**Comment by ActionPace** [comment] 2015-08-12 01:26
Thanks, that worked

**Comment by timholy** [comment] 2015-08-12 10:49
Fixed by #330. If you've fixed this locally, you'll prevent yourself from receiving updates unless you say `git checkout deps/build.jl`.

Then do `Pkg.update()`.

**Closed** 2015-08-12 10:50 UTC

**Comment by Timmmm** [comment] 2015-12-07 10:04
I have this problem using the latest Juno release. I checked line 35 and it does use the '>' pattern. It looks like [the imagemagick site](http://www.imagemagick.org/download/binaries) has all been updated on the 5th of December. Also ImageMagick 7 has been released.

**Comment by Timmmm** [comment] 2015-12-07 10:14
The issue is that you were searching the text of the links, rather than their URLs. They've now been elided so the regex no longer works. Using this pattern "fixed" it:

        pattern = "\"ImageMagick-6\.9.*-Q16-$(OS_ARCH)-dll.exe\""

But in general this is a terrible way to automatically download software. It would be much better if a copy was hosted at a known URL - I note that innounp is already hosted at AWS, so why not put a copy of ImageMagick there too?

Also, why fetch and parse the downloads page to get a URL, when that URL is at least as fixed as the download page itself (as we have shown here). In other words, why not just directly download http://www.imagemagick.org/download/binaries/ImageMagick-6.9.2-8-Q16-$(OS_ARCH)-dll.exe ?

(I'm guessing the answer is "so you automatically get the latest version", but clearly that doesn't work anyway.)

Finally, I'm a Julia beginner, but I assume it has some form of error checking, so you can see if the download, regex, etc. worked and print a sane error message?

**Comment by timholy** [comment] 2015-12-09 01:51
A pull request to ImageMagick.jl would be great! Anything anyone can do to help figure out a good way to host binaries would be most welcome.

Images is now independent of ImageMagick. Further discussion should take place over at ImageMagick.jl.
